package com.skillcircle.auth.filter;

import com.skillcircle.auth.entity.User;
import com.skillcircle.auth.repository.UserRepository;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.security.web.authentication.SimpleUrlAuthenticationSuccessHandler;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponentsBuilder;

import java.io.IOException;
import java.util.Map;

/**
 * Handles successful OAuth2 authentication by redirecting back to the
 * React SPA with JWT tokens as URL parameters.
 *
 * The tokens were pre-generated by OAuth2UserService and stored in Redis.
 * This handler retrieves them and redirects to the frontend callback URL.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class OAuth2SuccessHandler extends SimpleUrlAuthenticationSuccessHandler {

    private static final String OAUTH_TOKEN_PREFIX = "oauth_tokens:";

    private final UserRepository userRepository;
    private final StringRedisTemplate redisTemplate;

    @Value("${app.cors.allowed-origins}")
    private String frontendUrl;

    @Override
    public void onAuthenticationSuccess(
            HttpServletRequest request,
            HttpServletResponse response,
            Authentication authentication
    ) throws IOException, ServletException {

        OAuth2AuthenticationToken oauthToken = (OAuth2AuthenticationToken) authentication;
        OAuth2User oAuth2User = oauthToken.getPrincipal();
        String registrationId = oauthToken.getAuthorizedClientRegistrationId();

        Map<String, Object> attributes = oAuth2User.getAttributes();
        String oauthId;
        String email;

        if ("github".equals(registrationId)) {
            oauthId = String.valueOf(attributes.get("id"));
            email = (String) attributes.get("email");
        } else { // google
            oauthId = (String) attributes.get("sub");
            email = (String) attributes.get("email");
        }

        // Find the user — try by OAuth provider+id first, then fall back to email
        com.skillcircle.auth.entity.AuthProvider provider =
                com.skillcircle.auth.entity.AuthProvider.valueOf(registrationId.toUpperCase());
        User user = userRepository.findByOauthProviderAndOauthId(provider, oauthId)
                .or(() -> {
                    if (email != null) {
                        return userRepository.findByEmail(email);
                    }
                    return java.util.Optional.empty();
                })
                .orElse(null);

        if (user == null) {
            log.error("OAuth user not found — provider={}, oauthId={}, email={}", provider, oauthId, email);
            response.sendRedirect(frontendUrl + "/auth/error?message=user_not_found");
            return;
        }

        // Retrieve pre-generated tokens from Redis
        String tokenKey = OAUTH_TOKEN_PREFIX + user.getId().toString();
        String accessToken = (String) redisTemplate.opsForHash().get(tokenKey, "accessToken");
        String refreshToken = (String) redisTemplate.opsForHash().get(tokenKey, "refreshToken");

        // Clean up
        redisTemplate.delete(tokenKey);

        if (accessToken == null || refreshToken == null) {
            log.error("OAuth tokens not found in Redis for user: {}", user.getUsername());
            response.sendRedirect(frontendUrl + "/auth/error?message=token_generation_failed");
            return;
        }

        // Redirect to frontend with tokens
        String redirectUrl = UriComponentsBuilder.fromUriString(frontendUrl + "/auth/callback")
                .queryParam("access_token", accessToken)
                .queryParam("refresh_token", refreshToken)
                .build()
                .toUriString();

        log.info("OAuth2 success — redirecting {} to frontend", user.getUsername());
        getRedirectStrategy().sendRedirect(request, response, redirectUrl);
    }
}
